#!/bin/sh

# PROVIDE: storagenode_updater
# REQUIRE: LOGIN FILESYSTEMS netwait
# KEYWORD: SHUTDOWN

. /etc/rc.subr

name=storagenode_updater
rcvar=${name}_enable


load_rc_config $name
: "${storagenode_updater_storage_path:="/mnt/storagenode"}"
: "${storagenode_updater_enable:=yes}"
: "${storagenode_updater_executable:="/usr/local/bin/storagenode-updater"}"
: "${storagenode_updater_node_binary_location:="/usr/local/bin/storagenode"}"
: "${storagenode_updater_node_service_name:="storagenode"}"
: "${storagenode_updater_config_dir:="${storagenode_updater_storage_path}/config"}"
: "${storagenode_updater_identity_dir:="${storagenode_updater_storage_path}/identity/storagenode"}"

pidfile="/var/run/${name}.pid"
pidfile_child="/var/run/${name}_child.pid"
command="/usr/sbin/daemon"
command_args="-f -H \
  -o \"/var/log/${name}.log\" \
  -P \"${pidfile}\" \
  -p \"${pidfile_child}\" \
  -u root \
  \"${storagenode_updater_executable}\" run \
    --config-dir \"${storagenode_updater_config_dir}\" \
    --identity-dir \"${storagenode_updater_identity_dir}\" \
    --binary-location \"${storagenode_updater_node_binary_location}\" \
    --service-name \"${storagenode_updater_node_service_name}\""

stop_cmd="${name}_stop"

storagenode_updater_stop()
{
#   This is needed to teardown our replacement updater, which runs in a shell interpreter,
#   that is known to ignore SIGTERM
    [ -e $pidfile_child  ] && kill -s SIGINT `cat $pidfile_child` && rm $pidfile_child
    [ -e $pidfile        ] && kill -s SIGINT `cat $pidfile`       && rm $pidfile
}

run_rc_command "$1"

