#!/bin/sh

# PROVIDE: storagenode_updater
# REQUIRE: LOGIN FILESYSTEMS netwait
# KEYWORD: shutdown

. /etc/rc.subr

name="storagenode_updater"
rcvar="${name}_enable"

: ${storagenode_updater_enable:="YES"}
: ${storagenode_updater_child_user:="root"}
: ${storagenode_updater_child_group:="wheel"}
: ${storagenode_updater_executable:="/usr/local/bin/storagenode-updater"}
: ${storagenode_updater_node_binary_location:="/usr/local/bin/storagenode"}
: ${storagenode_updater_node_service_name:="storagenode"}
: ${storagenode_updater_storage_path:="/mnt/storagenode"}
: ${storagenode_updater_config_dir:="${storagenode_updater_storage_path}/config"}
: ${storagenode_updater_identity_dir:="${storagenode_updater_storage_path}/identity/storagenode"}
: ${storagenode_updater_logfile:="/var/log/${name}.log"}

pidfile="/var/run/${name}.pid"
command="/usr/sbin/daemon"

start_precmd="${name}_prestart"
storagenode_updater_prestart()
{
    # Ensure logfile exists with proper perms
    install -o "${storagenode_updater_child_user}" -g "${storagenode_updater_child_group}" -m 644 /dev/null "${storagenode_updater_logfile}"

    # Required dirs must exist
    for d in \
        "${storagenode_updater_storage_path}" \
        "${storagenode_updater_config_dir}" \
        "${storagenode_updater_identity_dir}"
    do
        if [ ! -d "$d" ] || [ ! -w "$d" ]; then
            err 1 "Required directory '$d' missing or not writable"
        fi
    done
}

command_args="-f -H \
  -o ${storagenode_updater_logfile} \
  -P ${pidfile} \
  -u ${storagenode_updater_child_user} \
  ${storagenode_updater_executable} run \
    --config-dir ${storagenode_updater_config_dir} \
    --identity-dir ${storagenode_updater_identity_dir} \
    --binary-location ${storagenode_updater_node_binary_location} \
    --service-name ${storagenode_updater_node_service_name}"

run_rc_command "$1"
