#!/bin/sh

# PROVIDE: storj
# REQUIRE: LOGIN FILESYSTEMS netwait
# KEYWORD: SHUTDOWN

. /etc/rc.subr

name=storj
rcvar=storj_enable


load_rc_config $name
: ${storj_enable:=yes}
: ${storj_executable:="/usr/local/bin/storagenode"}
: ${storj_msg:="Nothing started."}
: ${storj_storage_path:="/mnt/storj"}
: ${storj_config_dir:="${storj_storage_path}/config"}
: ${storj_identity_dir:="${storj_storage_path}/identity/storagenode"}

pidfile="/var/run/${name}.pid"
command="/usr/sbin/daemon"
command_args="-r -f -H -o \"/var/log/${name}.log\" \
    -P \"${pidfile}\" -u root \"${storj_executable}\" run \
    --config-dir \"${storj_config_dir}\" \
    --identity-dir \"${storj_identity_dir}\"\
    --log.level info --log.output stdout \
    --storage.path \"${storj_storage_path}\""

required_dirs="${storj_storage_path}/blobs"

run_rc_command "$1"
