#!/bin/sh

# PROVIDE: storjupd
# REQUIRE: LOGIN FILESYSTEMS netwait
# KEYWORD: SHUTDOWN

. /etc/rc.subr

name=storjupd
rcvar=${name}_enable


load_rc_config $name
: ${storjupd_storage_path:="/mnt/storj"}
: ${storjupd_enable:=yes}
: ${storjupd_executable:="/usr/local/bin/storagenode-updater"}
: ${storjupd_node_binary_location:="/usr/local/bin/storagenode"}
: ${storjupd_node_service_name:="storj"}
: ${storjupd_config_dir:="${storjupd_storage_path}/config"}
: ${storjupd_identity_dir:="${storjupd_storage_path}/identity/storagenode"}

pidfile="/var/run/${name}.pid"
command="/usr/sbin/daemon"
command_args="-f -H -o \"/var/log/${name}.log\" \
    -P \"${pidfile}\" -u root \"${storjupd_executable}\" run \
    --config-dir \"${storjupd_config_dir}\" \
    --identity-dir \"${storjupd_identity_dir}\"\
    --binary-location \"${storjupd_node_binary_location}\" \
    --service-name \"${storjupd_node_service_name}\"" 


run_rc_command "$1"

